name: testbojan
favicon: null
layout_spectrum: 0.9868168123066425
typography_spectrum: 0.4477706206962466
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5495419586077332
  lightness: 0.14961841935291886
  saturation: 0.6632431447505951
  rhythmicContrast: 0.23176587908528745
purpose: []
