name: testbojan
favicon: null
layout_spectrum: 0.30441
typography_spectrum: 0.13044
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e1d6d4'
    - '#37332d'
    - '#9a8e86'
    - '#c1b4b5'
    - '#706160'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
